"""Turns a picture into the still image on the right half's nice!view screen.

Run:  python screen/make_image.py            (needs Pillow: pip install pillow)
  screen/husky_source.png  ->  boards/shields/nice_view_gem/assets/peripheral_image.c
                               screen/preview.png (4x, coloured like the screen)

The picture area is 68 wide x 69 tall as you look at the board, pure black and white. The screen is mounted sideways,
so the image is stored turned 90 degrees clockwise (69 x 68), like the gem's crystal frames were.
Style: autocontrast + Floyd-Steinberg dither ("A" from the 2026-10-03 previews).
"""
import os

from PIL import Image, ImageOps

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "husky_source.png")
CROP = (4, 0, 148, 146)           # the face, same shape as the 68 x 69 area
OUT_C = os.path.join(HERE, "..", "boards", "shields", "nice_view_gem", "assets", "peripheral_image.c")
OUT_PREVIEW = os.path.join(HERE, "preview.png")
W, H = 68, 69                     # upright, as seen on the board


def picture():
    img = Image.open(SRC).convert("L").crop(CROP).resize((W, H), Image.LANCZOS)
    return ImageOps.autocontrast(img, cutoff=2).convert("1")      # dithered; black pixels are drawn


def c_source(img):
    stored = img.transpose(Image.ROTATE_270)                        # 90 degrees clockwise -> 69 x 68
    w, h = stored.size
    stride = (w + 7) // 8
    data = bytearray(stride * h)
    px = stored.load()
    for y in range(h):
        for x in range(w):
            # On the real screen a 1 bit shows light and a 0 bit dark (checked on the board 2026-10-03: the
            # first build, with 1 = dark, came out as a negative), so set the bit for light pixels.
            if px[x, y] != 0:
                data[y * stride + x // 8] |= 0x80 >> (x % 8)
    rows = [", ".join("0x%02x" % b for b in data[i:i + 15]) for i in range(0, len(data), 15)]
    body = ",\n        ".join(rows)
    return """// Generated by screen/make_image.py from screen/%s; do not edit by hand.
#include <lvgl.h>

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST uint8_t peripheral_image_map[] = {
#if CONFIG_NICE_VIEW_WIDGET_INVERTED
        0x00, 0x00, 0x00, 0xff, /*Color of index 0*/
        0xff, 0xff, 0xff, 0xff, /*Color of index 1*/
#else
        0xff, 0xff, 0xff, 0xff, /*Color of index 0*/
        0x00, 0x00, 0x00, 0xff, /*Color of index 1*/
#endif

        %s,
};

const lv_img_dsc_t peripheral_image = {
    .header.cf = LV_IMG_CF_INDEXED_1BIT,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = %d,
    .header.h = %d,
    .data_size = %d,
    .data = peripheral_image_map,
};
""" % (os.path.basename(SRC), body, w, h, len(data) + 8)


def preview(img, scale=4):
    light = Image.new("RGB", img.size, (200, 203, 198))
    dark = Image.new("RGB", img.size, (30, 32, 35))
    return Image.composite(light, dark, img.convert("L")).resize((W * scale, H * scale), Image.NEAREST)


def main():
    img = picture()
    with open(OUT_C, "w", encoding="utf-8", newline="\n") as f:
        f.write(c_source(img))
    preview(img).save(OUT_PREVIEW)
    print("wrote", os.path.normpath(OUT_C))
    print("wrote", OUT_PREVIEW)


if __name__ == "__main__":
    main()
